export const PAYMENT_AMOUNT_OPTIONS   = [100, 200, 500, 1000];
export const FAVOURITE_LIMIT          = 5;
export const DEFAULT_LANGUAGE         = 'pt';
export const MINIMUM_AMOUNT           = 10;
export const MAXIMUM_AMOUNT           = 25000;
export const MAXIMUM_AMOUNT_LABEL     = "25,000";
export const LS_ONBOARDING_KEY        = 'crd_onbrd';
export const CURRENCY                 = 'MT';
export const DASHBOARD_NUM_PAYMENTS   = 5;

// Service Provider Configs
export const SHORTCODE                = '020002'; // Service Provider Shortcode
export const EXTERNAL_API             = '/service-adapter/v1/generic/proxy/external/BusinessApp';
export const EXTERNAL_API_PAYMENT     = '/service-adapter/v1/generic/proxy/external/PAY_CREDELEC';
export const EXTERNAL_API_PDF         = 'https://gateway.wit.m-pesa.vm.co.mz/mini-apps-generic-service/v2/documents/pdf';

// Error codes
export const APP_ERRORS = {
  AMOUNT_TOO_LOW: 'AMOUNT_TOO_LOW',
  AMOUNT_TOO_HIGH: 'AMOUNT_TOO_HIGH',
  LIMIT_EXCEEDED: 'LIMIT_EXCEEDED',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  INVALID_RECEIVER: 'INVALID_RECEIVER',
  INVALID_PARAMETERS: 'INVALID_PARAMETERS',
  WRONG_PIN: 'WRONG_PIN',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  UNKNOWN: 'UNKNOWN',
}

export const API_ERROR_CODES_MAPPING = {
  '2007': APP_ERRORS.AMOUNT_TOO_LOW,
  '2008': APP_ERRORS.AMOUNT_TOO_LOW,
  '400-10': APP_ERRORS.AMOUNT_TOO_HIGH,
  '400-12': APP_ERRORS.LIMIT_EXCEEDED,
  '2006': APP_ERRORS.INSUFFICIENT_BALANCE,
  '400-9': APP_ERRORS.INSUFFICIENT_BALANCE,
  '403-18': APP_ERRORS.INSUFFICIENT_BALANCE,
  '2002': APP_ERRORS.INVALID_RECEIVER,
  '400-24': APP_ERRORS.INVALID_RECEIVER,
  '400-29': APP_ERRORS.INVALID_RECEIVER,
  '400-58': APP_ERRORS.INVALID_PARAMETERS,
  '2001': APP_ERRORS.WRONG_PIN,
  '400-22': APP_ERRORS.WRONG_PIN,
  '1000': APP_ERRORS.SERVICE_UNAVAILABLE,
  '1001': APP_ERRORS.SERVICE_UNAVAILABLE,
  '2011': APP_ERRORS.SERVICE_UNAVAILABLE,
  '-20': APP_ERRORS.SERVICE_UNAVAILABLE,
  '-8': APP_ERRORS.SERVICE_UNAVAILABLE,
  '-2': APP_ERRORS.SERVICE_UNAVAILABLE,
  '400-14': APP_ERRORS.SERVICE_UNAVAILABLE,
  '408-0': APP_ERRORS.SERVICE_UNAVAILABLE,
  '408-3': APP_ERRORS.SERVICE_UNAVAILABLE,
  '500-10': APP_ERRORS.SERVICE_UNAVAILABLE,
  '500-14': APP_ERRORS.SERVICE_UNAVAILABLE,
  '500-25': APP_ERRORS.SERVICE_UNAVAILABLE,
}
